sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 1234
  #阿里云配置项
  alioss:
    endpoint:
    access-key-id:
    access-key-secret:
    bucket-name:
  redis:
    host: localhost
    port: 6379
  sky:
    wechat:
      appid: wxffb3637a228223b8
      secret: 84311df9199ecacdf4f12d27b6b9522d